config/routes.rb
Sampleapp::Application.routes.draw do
  
  resources :users  
  resources :sessions, only: [:new, :create, :destroy]
  resources :block_towers
  resources :blocks

  root to: 'static_pages#home'
  match '/signup',   to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete
  match '/help',     to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',  to: 'static_pages#contact'
  match '/blocks',   to: 'static_pages#blocks'

end

app/models/block.rb
# == Schema Information
#
# Table name: blocks
#
#  id             :integer          not null, primary key
#  block_tower_id :integer
#  position       :integer
#  name           :string(255)
#  time           :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Block < ActiveRecord::Base
  attr_accessible :block_tower_id, :name, :position, :time

belongs_to :block_tower

acts_as_list :scope => :block_tower

end

app/models/block_tower.rb
# == Schema Information
#
# Table name: block_towers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class BlockTower < ActiveRecord::Base
  attr_accessible :name, :user_id

  has_many :blocks, :order => :position
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token  


  validates :name, presence: true, length: { maximum: 32 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  has_many :block_towers


  private
 
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/block_towers_controller.rb
class BlockTowersController < ApplicationController
  def new
     @block_tower = BlockTower.new
  end

  def show
     @block_tower = BlockTower.find(params[:user_id])
  end

  def index
  end

  def create
    @block_tower = current_user.block_towers.build(params[:block_tower])
    if @block_tower.save
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def edit
  end

  def update
    if @block_tower.update_attributes(params[:block_tower])
      redirect_to @block_tower
    else
      render 'edit'
    end
  end

  def destroy
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def new
     @block = Block.new
  end

  def show
     @block = Block.find(params[:user_id])
  end

  def index
  end

  def create
    @block = current_user.block_towers.build(params[:block])
    if @block.save
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def edit
  end

  def update
    if @block.update_attributes(params[:block])
      redirect_to @block
    else
      render 'edit'
    end
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
before_filter :signed_in_user, only: [:index, :edit, :update]
before_filter :correct_user,   only: [:edit, :update]
 
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the TodayBlocks!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

private
 
  def signed_in_user
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   # returns the full title on a per page basis#
    def full_title(page_title)
     base_title = "TodayBlocks"
     if page_title.empty?
       base_title
     else
       "#{base_title} | #{page_title}"
     end
    end
end

app/helpers/block_towers_helper.rb
module BlockTowersHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/block_towers/create.html.erb
<h1>BlockTowers#create</h1>
<p>Find me in app/views/block_towers/create.html.erb</p>

app/views/block_towers/edit.html.erb
<h1>BlockTowers#edit</h1>
<p>Find me in app/views/block_towers/edit.html.erb</p>

app/views/block_towers/index.html.erb
<h1>BlockTowers#index</h1>
<p>Find me in app/views/block_towers/index.html.erb</p>

app/views/block_towers/new.html.erb
<h1>BlockTowers#new</h1>
<p>Find me in app/views/block_towers/new.html.erb</p>

app/views/block_towers/show.html.erb
<h1>BlockTowers#show</h1>
<p>Find me in app/views/block_towers/show.html.erb</p>

app/views/block_towers/update.html.erb
<h1>BlockTowers#update</h1>
<p>Find me in app/views/block_towers/update.html.erb</p>

app/views/blocks/create.html.erb
<h1>Blocks#create</h1>
<p>Find me in app/views/blocks/create.html.erb</p>

app/views/blocks/destroy.html.erb
<h1>Blocks#destroy</h1>
<p>Find me in app/views/blocks/destroy.html.erb</p>

app/views/blocks/index.html.erb
<h1>Blocks#index</h1>
<p>Find me in app/views/blocks/index.html.erb</p>

app/views/blocks/new.html.erb
<h1>Blocks#new</h1>
<p>Find me in app/views/blocks/new.html.erb</p>

app/views/blocks/show.html.erb
<h1>Blocks#show</h1>
<p>Find me in app/views/blocks/show.html.erb</p>

app/views/blocks/update.html.erb
<h1>Blocks#update</h1>
<p>Find me in app/views/blocks/update.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TODAY BLOCKS", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
    <h1>About Us</h1>
    <p>
      <a href="http://todayblocks.herokuapp.com/">Today Blocks</a>
      is a time management app being developed by
      <a href="http://brianindig.com/">Brian Indig</a>. 
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you feel the need to contact me, alter the @: brindigATgmail.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help')%>
    <h1>Help</h1>
    <p>

      Help(page) is on the way!
    </p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Today Blocks</h1>

  <h2>
  Ready to plan your day? Great! 
  </h2>

  <%= link_to "Sign up!", 'signup', class: "btn btn-large btn-primary" %>
  <%= link_to "I don't have time to sign up. LET'S GO!", 'blocks', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/static_pages/main.html.erb
<% provide(:title, 'Control Panel')%>


<div class="center hero-unit">

  <h2>
  TodayBlocks Control Panel
  </h2>

  <%= %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>
<%= @user.name %>, <%= @user.email %>